enum SportActionType {
  GET_SPORTS_START = 'GET_SPORTS_START',
  GET_SPORTS_SUCCESS = 'GET_SPORTS_SUCCESS',
  GET_SPORTS_FAIL = 'GET_SPORTS_FAIL',
  ADD_LIKE_SPORT_START = 'ADD_LIKE_SPORT_START',
  ADD_LIKE_SPORT_SUCCESS = 'ADD_LIKE_SPORT_SUCCESS',
  ADD_LIKE_SPORT_FAIL = 'ADD_LIKE_SPORT_FAIL',
  GET_LIKED_SPORTS_START = 'GET_LIKED_SPORTS_START',
  GET_LIKED_SPORTS_SUCCESS = 'GET_LIKED_SPORTS_SUCCESS',
  GET_LIKED_SPORTS_FAIL = 'GET_LIKED_SPORTS_FAIL',
}

export default SportActionType
